# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Titanium < Formula
  desc "Titanium CLI (ti): powerful toolkit for platform operations"
  homepage "https://github.com/titan-syndicate/titanium"
  version "0.1.11-rc.abd7395"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.abd7395/titanium_0.1.11-rc.abd7395_darwin_amd64.tar.gz"
      sha256 "28a4f3fbe31b98244c8ff58bd9c8c93f52bc2b8fc5e30c087b518f1b8e7d93f7"

      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.abd7395/titanium_0.1.11-rc.abd7395_darwin_arm64.tar.gz"
      sha256 "26aa9829dc2f89e78bfac7718aec75cb24847145a21a4b356f3d13a096f0849c"

      def install
        bin.install "ti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.abd7395/titanium_0.1.11-rc.abd7395_linux_amd64.tar.gz"
      sha256 "220532ad7b5a9e502553cab408dab671df42ebde8a240dc88407aa035e88d873"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.abd7395/titanium_0.1.11-rc.abd7395_linux_arm.tar.gz"
      sha256 "88e90ec0650592b636a693a2765fe8f318652f403eac6e64196f5baf1d635da0"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.abd7395/titanium_0.1.11-rc.abd7395_linux_arm64.tar.gz"
      sha256 "090fdb6e6c8f4a58fc329fb151dcc51ebbf3b0f67f1d829720362f63d55287e3"
      def install
        bin.install "ti"
      end
    end
  end

  test do
    system "#{bin}/ti", "--version"
  end
end
