# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Titanium < Formula
  desc "Titanium CLI (ti): powerful toolkit for platform operations"
  homepage "https://github.com/titan-syndicate/titanium"
  version "0.1.11-rc.4dda4e2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.4dda4e2/titanium_0.1.11-rc.4dda4e2_darwin_amd64.tar.gz"
      sha256 "4efc43f8907822ede985ba60f3beb32fbecca9b2048f14569381319315082041"

      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.4dda4e2/titanium_0.1.11-rc.4dda4e2_darwin_arm64.tar.gz"
      sha256 "cd0b9d0f2de68e2fe2af1904151010807d54d978b30979f14ae17b9985413c54"

      def install
        bin.install "ti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.4dda4e2/titanium_0.1.11-rc.4dda4e2_linux_amd64.tar.gz"
      sha256 "833ad2067f56cf0a216f18c988baf46eb94a3a3d9bf9f4fccbc692a60f682b46"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.4dda4e2/titanium_0.1.11-rc.4dda4e2_linux_arm.tar.gz"
      sha256 "6e7a2a164ae88f7495cbe94da47c433c9023f147f16d8ecb9e6462d1530ba59e"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.4dda4e2/titanium_0.1.11-rc.4dda4e2_linux_arm64.tar.gz"
      sha256 "ad7d2a8118273337037088f6d3d88ebcdf0403deff8185816e4c708346c98818"
      def install
        bin.install "ti"
      end
    end
  end

  test do
    system "#{bin}/ti", "--version"
  end
end
