# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TitaniumAT021 < Formula
  desc "Titanium CLI (ti): powerful toolkit for platform operations"
  homepage "https://github.com/titan-syndicate/titanium"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.2.1/titanium_0.2.1_darwin_amd64.tar.gz"
      sha256 "123af66b4064c93723e68f4cb331e57f1a19ad80779f99ec593d155d1b435247"

      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.2.1/titanium_0.2.1_darwin_arm64.tar.gz"
      sha256 "28e6e25659fab35fe3c73db9e11dbdd7318f08966d6d2893cf54aaec8841eae9"

      def install
        bin.install "ti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.2.1/titanium_0.2.1_linux_amd64.tar.gz"
      sha256 "4395ad21da4c04291ac16c4e0f076dc0549b2947ff097594ee62d15cd385438c"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.2.1/titanium_0.2.1_linux_arm.tar.gz"
      sha256 "1db60a8d6d878a60e9cd315a98b9ca526f4b8a3ec37f38e01efa6f56eaa7c886"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.2.1/titanium_0.2.1_linux_arm64.tar.gz"
      sha256 "bf3a79ebb089b6771aa1cda44e40e52e424b819117c5bc401969f0228945d1d8"
      def install
        bin.install "ti"
      end
    end
  end

  test do
    system "#{bin}/ti", "--version"
  end
end
