# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TitaniumAT0111Rc2fdd6bd < Formula
  desc "Titanium CLI (ti): powerful toolkit for platform operations"
  homepage "https://github.com/titan-syndicate/titanium"
  version "0.1.11-rc.2fdd6bd"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.2fdd6bd/titanium_0.1.11-rc.2fdd6bd_darwin_amd64.tar.gz"
      sha256 "9fb7e8411f2ac000618f56f2e35b7ac08edb255f6bfd49b8112b255246b867b5"

      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.2fdd6bd/titanium_0.1.11-rc.2fdd6bd_darwin_arm64.tar.gz"
      sha256 "2cc3c47c3356ddcd3cf527f6f93d29bb40fcadc6d3ca661afabd2db2fe5b63d1"

      def install
        bin.install "ti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.2fdd6bd/titanium_0.1.11-rc.2fdd6bd_linux_amd64.tar.gz"
      sha256 "e5b2baa25b0596a0486bb5bcddcc94b77c8ef55c3d4a70bcab77d8b64036d5fa"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.2fdd6bd/titanium_0.1.11-rc.2fdd6bd_linux_arm.tar.gz"
      sha256 "2b2e8840f4f2afcd48cd37e56c9cc04708e5acdb99ef690262e8fc3ebd852bf6"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.2fdd6bd/titanium_0.1.11-rc.2fdd6bd_linux_arm64.tar.gz"
      sha256 "8f89bc3a0a4e0bb4ae8d540c84e13c0212692723169be35f20946cddaecc4ca1"
      def install
        bin.install "ti"
      end
    end
  end

  test do
    system "#{bin}/ti", "--version"
  end
end
