# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TitaniumAT0 < Formula
  desc "Titanium CLI (ti): powerful toolkit for platform operations"
  homepage "https://github.com/titan-syndicate/titanium"
  version "0.1.11-rc.dce162d"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.dce162d/titanium_0.1.11-rc.dce162d_darwin_amd64.tar.gz"
      sha256 "fa5e2c251796c928e56605bdf525e1c5ac6d65b9002a039232666784c09cb4f4"

      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.dce162d/titanium_0.1.11-rc.dce162d_darwin_arm64.tar.gz"
      sha256 "c00e1c0ad37e78c1dae600dbfc290d43fe2da52b84710cfb33cc31e24c232bc0"

      def install
        bin.install "ti"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.dce162d/titanium_0.1.11-rc.dce162d_linux_amd64.tar.gz"
      sha256 "79c9cec52fe9ec771df190ec38cba8c46db6534d1fa8cea7c889a3469a55d4c8"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.dce162d/titanium_0.1.11-rc.dce162d_linux_arm.tar.gz"
      sha256 "e14906ee4c2890849229061504e23c0e3a441db8f9a8a6a0802ff6e118b27bd4"
      def install
        bin.install "ti"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/titan-syndicate/titanium/releases/download/v0.1.11-rc.dce162d/titanium_0.1.11-rc.dce162d_linux_arm64.tar.gz"
      sha256 "c3461b8a683c4f6bc27244b61c9a334021bc5f3440274a7dfc91d0867d543fb8"
      def install
        bin.install "ti"
      end
    end
  end

  test do
    system "#{bin}/ti", "--version"
  end
end
